### ISSUE TITLE
Uncaught ReferenceError: AeroGear is not defined 

### ISSUE THREAD

**Issue by nazrdogan** [aerogear/aerogear-cordova-crypto#8]
I m developing android app. I added plugin  using 
cordova plugin add https://github.com/edewit/aerogear-crypto-cordova

 and defined in index.html
 
 <script>
        var agCrypto = AeroGear.Crypto();
    </script>

it gives me 
Uncaught ReferenceError: AeroGear is not defined 

what can I do for it. should I refence any library in index.html ?

is there any sample app for crypto ?

**Comment by matzew** [comment]
@nazrdogan Hi, I have created a JIRA ticket for htis: https://issues.jboss.org/browse/AGCORDOVA-81

**Comment by edewit** [comment]
hi @nazrdogan could you try to install the released version of the plugin?
by running
```cmd
cordova plugin add org.jboss.aerogear.cordova.crypto
```
you are now using my fork, which is a bit out dated
